name: Test External Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run External Custom Action
        uses: nehama1020-web/repo1/.github/actions/say-hello@main
        with:
          who: 'Neha'
